#!/usr/bin/env python
import signal
import sys

line_counter = 0

def timeout(signum, frame):
    global line_counter
    print "%d lines/sec" % line_counter
    line_counter = 0
    signal.alarm(1)

signal.signal(signal.SIGALRM, timeout)
signal.alarm(1)

while True:
    try:
        sys.stdin.readline()
    except IOError:
        pass
    else:
        line_counter += 1
